version: '3.8'

services:
  postgres:
    image: ankane/pgvector
    container_name: ai_agent_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: myagentdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - D:/safeharbor-postgres/data:/var/lib/postgresql/data
    restart: unless-stopped
