# App Environment
app:
  name: "Safe Harbor EDGAR AI Platform"
  environment: "development"  # Options: development, staging, production
  log_level: "DEBUG"

# Database Settings
database:
  url: ${DATABASE_URL}  # Example: postgres://user:password@localhost:5432/myagentdb

# Vector Store Settings (pgvector)
vector_store:
  table_name: "filing_vectors"
  embedding_dimensions: 1536
  distance_function: "cosine"

# Storage Paths\
storage:
  # ⚠️ Set to ./test_data/ to run in TEST mode, otherwise use ./data/
  # Only change manually during testing — this value is not overridden via CLI
  base_data_path: "./test_data/"

  # Subfolder routing for raw + cleaned + parsed
  raw_html_base_path: "data/raw/"
  cleaned_base_path: "data/cleaned/"
  parsed_base_path: "data/parsed/"

  # Subfolder formatting templates
  raw_subfolder_template: "{year}/{cik}/{form_type}/{accession_or_subtype}/"
  cleaned_subfolder_template: "{year}/{cik}/{form_type}/{accession_or_subtype}/"
  parsed_subfolder_template: "{year}/{cik}/{form_type}/{accession_or_subtype}/"

  # Reference data
  company_mapping_path: "data/reference/company_tickers.json"

# SEC Downloader Settings
sec_downloader:
  base_url: "https://www.sec.gov/Archives/"
  user_agent: "SafeHarborBot/1.0 (kris@safeharborstocks.com)"
  request_delay_seconds: 0.2

# Ingestion Settings
ingestion:
  use_rss_feed: true
  use_daily_index: true
  use_form_type_rules: false  # ✅ NEW: dynamically apply from form_type_rules.yaml
  include_optional_forms: false  # ✅ NEW: toggle to include optional.form_types
  # Use form_type 424B1 for IPO monitoring pipeline.
  filing_forms_to_track: [
    "8-K", "10-K", "10-Q", "S-1", "3", "4", "5", "13D", "13G", "20-F", "6-K", "13F-HR", "424B1", "S-4", "DEF 14A", "SC TO-I",
    "424B3", "424B4", "424B5", 
    ]
  apply_global_filter: false
  chunk_max_tokens: 4000
  save_cleaned_html: true
  save_raw_html: false

# Exhibit Parser Settings
exhibit_parser:
  remove_tables: true
  strip_whitespace: true
  header_labeling: true

# XBRL Ingestion (Future Work)
xbrl_ingestion:
  enabled: false
  base_url: "https://data.sec.gov/api/xbrl/companyfacts"
  backfill_years: 5

crawler_idx:
  # Default list of form types to include when --include_forms is not specified
  # This is used by all collector and orchestrator classes for filtering
  include_forms_default: [
    "8-K", "10-K", "10-Q", "S-1", "3", "4", "5", "13D", "13G", "20-F", "6-K", "13F-HR", "424B1", "S-4", "DEF 14A", "SC TO-I",
    "424B3", "424B4", "424B5", 
    ]